;; This logfile was generated automatically by `xindy'
;; at 12.07.2023  10:58:32
;; Indexstyle: "/tmp/qE3Ck3IOZS", Rawindex: "/tmp/K5EsUyh68C", Output: "1-BPM-2023.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ëœ" -> "R"
Letter-group: "¤€††È" -> "H"
Letter-group: "ÈÈË" -> "P"
Letter-group: "ÈÈËÃ" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤€††È" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÈÈË" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ëœ" -> "R"