This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./2-PSA-2023.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file 2-PSA-2023.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (15 comparisons).
Generating output file 2-PSA-2023.acr....done (16 lines written, 0 warnings).
Output written in 2-PSA-2023.acr.
Transcript written in 2-PSA-2023.alg.
