;; This logfile was generated automatically by `xindy'
;; at 12.05.2023  14:36:24
;; Indexstyle: "C:\\Users\\Usuario\\Documents\\SISTEMA DE GESTION DE CALIDAD\\2023-SGC-2\\7 - Alérgenos\\h2cqbPIZox", Rawindex: "C:\\Users\\Usuario\\Documents\\SISTEMA DE GESTION DE CALIDAD\\2023-SGC-2\\7 - Alérgenos\\v3FGsPDD0J", Output: "7 - ALE.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ëœ|" -> "R"
Letter-group: "ËÚ—|" -> "R"
Letter-group: "ÈÈËÃ|" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÈÈËÃ|" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ëœ|" -> "R"