;; This logfile was generated automatically by `xindy'
;; at 11.07.2023  08:37:31
;; Indexstyle: "/tmp/SsdCuz0KG7", Rawindex: "/tmp/mpCDE45n1D", Output: "10-FoodDefense-2023.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ëœ" -> "R"
Letter-group: "ÈÈËÃ" -> "P"
Letter-group: "¤€††È" -> "H"
Letter-group: "„È" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„È" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤€††È" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÈÈËÃ" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ëœ" -> "R"