;; This logfile was generated automatically by `xindy'
;; at 13.04.2023  10:43:56
;; Indexstyle: "C:\\Users\\Usuario\\Documents\\SISTEMA DE GESTION DE CALIDAD\\2023-SGC-2\\10 - Food Defense\\b_vUjns5NX", Rawindex: "C:\\Users\\Usuario\\Documents\\SISTEMA DE GESTION DE CALIDAD\\2023-SGC-2\\10 - Food Defense\\yjKzeUfRLo", Output: "10-FoodDefense-2023.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ëœ" -> "R"
Letter-group: "ÈÈËÃ" -> "P"
Letter-group: "¤€††È" -> "H"
Letter-group: "„È" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„È" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤€††È" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÈÈËÃ" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ëœ" -> "R"