;; This logfile was generated automatically by `xindy'
;; at 12.05.2023  09:43:54
;; Indexstyle: "C:\\Users\\Usuario\\Documents\\SISTEMA DE GESTION DE CALIDAD\\2023-SGC-2\\4 - VyPD\\YDNbnb6DDV", Rawindex: "C:\\Users\\Usuario\\Documents\\SISTEMA DE GESTION DE CALIDAD\\2023-SGC-2\\4 - VyPD\\snFXp32T6A", Output: "4 - VyPQ.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "ÈÈËÃ|" -> "P"
Letter-group: "Ëœ|" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÈÈËÃ|" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ëœ|" -> "R"